<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WINDOWS-H1PLS2E" name="com.bss.calcapiTest.CalciAPITestNG_Jul11" tests="2" failures="1" timestamp="19 Jul 2015 19:59:59 GMT" time="0.100" errors="0">
  <testcase name="f" time="0.047" classname="com.bss.calcapiTest.CalciAPITestNG_Jul11"/>
  <testcase name="testMult" time="0.053" classname="com.bss.calcapiTest.CalciAPITestNG_Jul11">
    <failure type="java.lang.AssertionError" message="------------------------Testing fail method usage-----------------------">
      <![CDATA[java.lang.AssertionError: ------------------------Testing fail method usage-----------------------
	at org.testng.Assert.fail(Assert.java:94)
	at com.bss.calcapiTest.CalciAPITestNG_Jul11.testMult(CalciAPITestNG_Jul11.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testMult -->
</testsuite> <!-- com.bss.calcapiTest.CalciAPITestNG_Jul11 -->
